version: "3.2"

networks:
  cluster_net:
    external:
      name: cassandra-net

services:

  ################################################################
  # The Casandra cluster
  #   - cassandra-node1
  ################################################################
  cassandra-001:
    image: cassandra:3.11
    hostname: cassandra-001
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-001"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.hostname == node-001
    volumes:
      - ./data/1:/var/lib/cassandra
    networks:
      - cluster_net

  ################################################################
  # The Casandra cluster
  #   - cassandra-node2
  ################################################################
  cassandra-002:
    image: cassandra:3.11
    hostname: cassandra-002
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-002"
      CASSANDRA_SEEDS: "cassandra-001"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.hostname == node-002
    volumes:
      - ./data/2:/var/lib/cassandra
    networks:
      - cluster_net
